server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://voting-db:3306/voting?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: votinguser
    password: votingpass123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "/swagger-ui.html"
    operations-sorter: method

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
